@ExamScheduler.Server_HostAddress = http://localhost:5274

GET {{ExamScheduler.Server_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{ExamScheduler.Server_HostAddress}}}/api/Users/
Accept: application/json
###